---
- name: Check CentOS OS and version
  hosts: all
  gather_facts: yes
  tasks:
    - name: Check the CentOS version
      command: cat /etc/centos-release
      register: centos_version

    - name: Display the CentOS version
      debug:
        msg: "The CentOS version is: {{ centos_version.stdout }}"
