- hosts: all
  gather_facts: no
  become: false
  tasks:

    - command: cp -r /home/ansible/2022 /tmp/ ; cd /tmp ; yum localinstall *.rpm -y

 
 
 


      register: out



    - debug:
         msg: '{{ out.stdout_lines }}'
