- hosts: all
  gather_facts: no
  become: True
  tasks:

    - command: cd /jobs/share/ITtest/Maya_2022_Linux/packages ; yum -y localinstall *.rpm 
      register: out

    - debug:
         msg: '{{ out.stdout_lines }}'
