- hosts: all
  gather_facts: no
  become: false
  tasks:

    - command: cd /jobs/share/ITtest/Maya_2022_Linux/packages ; yum localinstall *.rpm -y
 
 
 


      register: out



    - debug:
         msg: '{{ out.stdout_lines }}'
