---
- hosts: all
  become: true  

  tasks:
    - name: Install RPM package
      yum:  # Use the yum module for CentOS 7
        name: /jobs/share/ITtest/sai/nomachine_8.14.2_1_x86_64.rpm  
        state: present
      register: rpm_install_result

    - debug:
        msg: "RPM installation result: {{ rpm_install_result }}"
