---
- hosts: all
  become: true
  tasks:
       - name: Install NoMachine from local RPM (if not already installed)
      yum:
        name: /jobs/share/ITtest/sai/nomachine_8.16.1_1_x86_64.rpm  
        state: present
      when: nx_installed.results | length == 0 or nx_installed.results[0].version is not defined  # Check if package is absent or version is not defined

    - name: Start and enable the NoMachine service
      service:
        name: nxserver  # Or the actual service name if different
        state: started
        enabled: yes
