---
- name: Update all packages on Rocky Linux
  hosts: all
  become: true
  tasks:
    - name: Update all packages using yum
      yum:
        name: "*"
        state: latest
        update_cache: yes
