---
- hosts: all
  become: true
  gather_facts: true  # Ensure facts are gathered

  tasks:
    - name: Gather system information
      debug:
        msg:
          - "Hostname: {{ ansible_hostname }}"
          - "Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Kernel: {{ ansible_kernel }}"
          - "Architecture: {{ ansible_architecture }}"
          - "Total Memory: {{ ansible_mem_total_mb }} MB"
          - "CPU Cores: {{ ansible_processor_count }}"
          - "Uptime: {{ ansible_uptime_seconds }} seconds"
          - "Users: {{ ansible_users }}"
          - "Date and Time: {{ ansible_date_time.date }} {{ ansible_date_time.time }}"

    - name: Create HTML content
      set_fact:
        html_content: >-
          <!DOCTYPE html>
          <html>
          <head>
          <title>System Information</title>
          <style>
            body { font-family: sans-serif; }
            table { width: 80%; border-collapse: collapse; margin: 20px auto; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #f2f2f2; }
          </style>
          </head>
          <body>

          <h1>System Information</h1>

          <table>
            {% for item in debug.msg %}
            <tr>
              <td>{{ item.split(':')[0] }}</td>  <td>{{ item.split(':')[1] | trim }}</td> </tr>
            {% endfor %}
          </table>

          </body>
          </html>

    - name: Save HTML to file
      copy:
        content: "{{ html_content }}"
        dest: /tmp/system_info.html # Or any other path you prefer
        mode: 0644 # Set appropriate permissions

    - name: (Optional) Display the HTML content (for testing)
      debug:
        msg: "{{ html_content }}"

    - name: (Optional) Fetch the HTML file (if needed on your control machine)
      fetch:
        src: /tmp/system_info.html
        dest: ./system_info.html  # Local path on your control machine
        flat: yes
